apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ix5p4e2nf-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ix5p4e2nf-nodejs 
  name: ix5p4e2nf-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ix5p4e2nf-nodejs 
